<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
        <link rel="stylesheet" href="<?= $this->url->getBaseURI ();?>public/vendor/dist/css/bootstrap.min.css">
    </head>
<div class="container">
    <table class="table table-striped table-inverse">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Age</th>
                <th>Libfil</th>
            </tr>
        </thead>

        <tbody>
            <?php
            var_dump($value);
            foreach ($tab as $value)
                :
                ?>
                <tr>
                    <td><?= $value->nom ?></td>
                    <td><?= $value->prenom ?></td>
                    <td><?= $value->age ?></td>
                    <td><?= $value->filiere->libfil ?></td>
                </tr>
                <?php
                
            endforeach;
            ?>
        </tbody>
    </table>
</div>