<div class="container">

    <div id="accordion" role="tablist">
        <div class="card">
            <div class="card-header" role="tab" id="headingOne">
                <h5 class="mb-0">
                    <a class="collapsed" type="button" data-toggle="collapse" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        Ajouter une filiere
                    </a>
                </h5>
            </div>

            <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <form method="post" action="index/filiere">
                        <div class="form-group">
                            <label for="libfil">Libfil</label>
                            <input type="text" class="form-control" id="validationCustom01" placeholder=" Entrez le libellé de la filière" name="libfil" required autofocus>
                            <small id="passwordHelpInline" class="text-muted">
                                Soyez explicite Svp!!!
                            </small>
                            <br>
                            <button type="submit" class="btn btn-default">
                                Ajouter
                            </button>
                            <br>
                        </div>
                    </form>
                    <style>

                        #red{
                            position:absolute;
                            margin-top:30px; 
                            margin-left:10px; 
                        }
                        #espace{

                            margin:13px; 
                        }

                    </style>
                    <form id="red" method="post" action="index/delete">

                        <?php
                        $filiere = filiere::find();
                        foreach ($filiere as $value) {

                            echo '<input id ="espace" type="checkbox" name= "liste[]" value=' . $value->getId_fil() . '>' . '<br/>';
                        }
                        ?>
                        <br>
                        <button type="submit" class="btn btn-danger" data-target>Supprimer selection</button>
                    </form>
                    <table class="table table-striped table-inverse">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Libfil</th>
                                <th>Operation</th>
                            </tr>
                        </thead>

                        <tbody>

                            <?php
                            $filiere = filiere::find();
                            foreach ($filiere as $value) {
                                ?>
                                <tr>
                            <form method="post" action="index/delete">
                                <td><input type="hidden" name="liste[]" value="<?= $value->getId_fil() ?>" </td>
                                <td><?= $value->getLibfil() ?></td>
                                <td>
                                    <button type="submit" class="btn btn-danger" data-target>
                                        <span class="gliphycon gliphycon-remove"></span>
                                    </button>
                                </td>
                            </form>
                            <td>
                                <a href="index/modifier">
                                    <button class="btn btn-primary" data-target>
                                        <span class="gliphycon gliphycon-edit"></span>
                                    </button>
                                </a>
                            </td>
                            </tr>

                        <?php } ?>
                        </tbody>
                    </table>
                </div>
                <br>
                <br>
                <br>
                <br> 
                <p>
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        Etudiant
                    </button>
                </p>

                <div class="collapse" id="collapseExample">
                    <form method="post" action="index/etudiant">
                        <div class="card card-body">
                            <div class="col-md-6 mb-3">
                                <label for="validationCustom01">Nom</label>
                                <input type="text" class="form-control" id="validationCustom01" placeholder="Nom de l'étudiant" name="nom">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="validationCustom01">Prenom</label>
                                <input type="text" class="form-control" id="validationCustom01" placeholder="Prénom de l'étudiant" name="prenom">
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="validationCustom01">Age</label>
                                <input type="text" class="form-control" id="validationCustom01" placeholder="Age de l'étudiant" name="age">
                            </div>
                            <br>
                            <br>
                        </div>
                        <p>Choisisez votre filiere</p>
                            <select name="id_fil">
                                <?php
                                $filiere = filiere::find();
                                foreach ($filiere as $value) {
                                    ?>
                                    <option value=<?= $value->getId_fil() ?>><?= $value->libfil ?></option>
                                <?php } ?>
                            </select>
                        <br>
                        <br>
                        <button type="submit" class="btn btn-default">
                            Entrer
                        </button>
                    </form>
                    
                    <table class="table table-striped table-inverse">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nom</th>
                                <th>Prenom</th>
                                <th>Age</th>
                            </tr>
                        </thead>

                        <tbody>

                            <?php
                            $etudiant = etudiant::find();
                            foreach ($etudiant as $value) {
                                ?>
                                <tr>
                            <form method="post" action="index/etudiantdelete">
                                <td><input type="hidden" name="liste[]" value="<?= $value->getId_fil() ?>" </td>
                                <td><?= $value->getNom() ?></td>
                                <td><?= $value->getPrenom() ?></td>
                                <td><?= $value->getAge() ?></td>
                                <td>
                                    <button type="submit" class="btn btn-danger" data-target>
                                        <span class="gliphycon gliphycon-remove"></span>
                                    </button>
                                </td>
                            </form>
                            <td>
                                <a href="index/etmodifier">
                                    <button class="btn btn-primary" data-target>
                                        <span class="gliphycon gliphycon-edit"></span>
                                    </button>
                                </a>
                            </td>
                            </tr>

                        <?php } ?>
                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>

    </div>

    
    

</div>
